In [25]:
import google.generativeai as genai

genai.configure(api_key= 'AIzaSyDBECQnpdlHjyw0m90b8nMRBsA_oaE0WXU')
model = genai.GenerativeModel('gemini-1.5-pro-latest')

In [26]:
input_string = """
You are a data scientist working on a relation extraction task. Please do the following task and do not give output in the markdown format.One sample in relation extraction datasets consists of a relation, a context, a pair of head and tail entities in the context.The head entity has the relation with the tail entity.
Relation "person countries of residence" means a person is living in a country.
Here is an example:
Relation: person countries of residence
Context: iran 's top nuclear negotiator , ali larijani , was asked by state tv whether the country had started converting into gas a second batch of uranium , as it had planned to do at its isfahan nuclear facility .
Head Entity: ali larijani
Tail Entity: iran
Please generate 5 diversity samples (must have full : Relation , Context , Head Entity , Tail Entity) like the above example for the relation "person countries of residence":"""

In [27]:
generation_config = {
  "temperature": 0.0,
  "response_mime_type": "text/plain",
}

In [28]:
response = model.generate_content(input_string,generation_config=generation_config)

In [29]:
response.text

'Relation: person countries of residence\nContext: After fleeing the war in syria , the family settled in jordan , where they have been living for the past five years .\nHead Entity: the family\nTail Entity: jordan\n\nRelation: person countries of residence\nContext: Elon musk , the ceo of tesla and spacex , recently relocated to texas from california .\nHead Entity: Elon musk\nTail Entity: texas\n\nRelation: person countries of residence\nContext: Although she was born in argentina , she has lived in spain for most of her life and now considers madrid her home .\nHead Entity: she\nTail Entity: spain\n\nRelation: person countries of residence\nContext: My grandparents immigrated to canada from ireland in the 1950s and built a new life for themselves in toronto .\nHead Entity: My grandparents\nTail Entity: canada\n\nRelation: person countries of residence\nContext: The author , who currently resides in japan , draws inspiration for his novels from the rich cultural heritage of the count

In [21]:
import json

res = json.loads(response.text) 
res

[{'Relation': 'person countries of residence',
  'Context': 'russian president vladimir putin signed a decree on wednesday to expedite russian passports to residents of two regions of eastern ukraine , a move that could presage a russian military advance .',
  'Head Entity': 'vladimir putin',
  'Tail Entity': 'russia'},
 {'Relation': 'person countries of residence',
  'Context': 'in february 2021 , meghan markle accused the british royal family of racism .',
  'Head Entity': 'meghan markle',
  'Tail Entity': 'britain'},
 {'Relation': 'person countries of residence',
  'Context': 'during a visit to kyiv on saturday , british prime minister boris johnson announced a new package of military aid for ukraine .',
  'Head Entity': 'boris johnson',
  'Tail Entity': 'britain'},
 {'Relation': 'person countries of residence',
  'Context': 'the agreement was signed by chinese foreign minister wang yi and his solomon islands counterpart , jeremiah manele .',
  'Head Entity': 'jeremiah manele',
  'T

In [1]:
import torch
import numpy as np

a = torch.rand(5,7)
b = a.data.numpy()

type(a[0])

torch.Tensor

In [2]:
type(b[0])

numpy.ndarray

In [4]:
a = {}
a[0] = 5


In [5]:
a

{0: 5}

In [6]:
label = torch.tensor([1,2,3,4,5])

In [17]:
label.cpu().data.tolist()

[1, 2, 3, 4, 5]

In [18]:
label

tensor([1, 2, 3, 4, 5])

In [19]:
label.numpy()

array([1, 2, 3, 4, 5])

In [20]:
label

tensor([1, 2, 3, 4, 5])

In [22]:
a = np.random.randn(3,5)

In [25]:
a[0].shape

(5,)